=== Giri2802/Totest/web/newXMLDocument.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/newXMLDocument.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE EmployeeDetails SYSTEM "newXMLDocument.dtd">

    <EmployeeDetails>
    ...
    </EmployeeDetails>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT EmployeeDetails (Employee)*>
<!ELEMENT Employee (Name|Designation|Salary)*>
<!ATTLIST Employee
    id CDATA #IMPLIED  >
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Designation (#PCDATA)>
<!ELEMENT Salary (#PCDATA)>

=== Giri2802/Totest/web/newXMLDocument.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE EmployeeDetails SYSTEM "newXMLDocument.dtd">

<EmployeeDetails>
    <Employee id="Emp1">
        <Name>Giridhar</Name>
        <Designation>Software Trainee</Designation>
        <Salary>50000</Salary>
    </Employee>
    <Employee id="Emp2">
        <Name>Pavan</Name>
        <Designation>Software Trainee</Designation>
        <Salary>5000</Salary>
    </Employee>
</EmployeeDetails>
